body:
  - type: markdown
    attributes:
      value: |
        ## Proposals

        This form provides a **template** for proposal. It is intended to provide a structured way to document a proposal of a planned workpiece.

        In lieu of internal links (currently a limitation of Discussions), it is recommended that particularly large sections are wrapped in an expandable `<details>` element, like so:
        ```md
        ### Schema

        Brief description.

        <details><summary>See more...</summary>

        Expandable content (with a blank line separating from the opening/closing tags)

        </details>
        ```
  - type: textarea
    id: links
    attributes:
      label: Related Links
      description: |
        Link to the consideration discussion where this document was requested (if applicable), plus any other related discussions/issues.
      value: |
        **See also:**
        - Consideration: #
        - #
  - type: textarea
    id: estimate
    attributes:
      label: Estimate
      value: |
        **Classification**: [Update/Epic]
        **Max Engineers**: [1/1.5/2/2.5/3]
        **Size**: [S/M/L]
    validations:
      required: true
  - type: textarea
    id: value
    attributes:
      label: Value
      value: |
        **User**: [High/Medium/Low/None] - [Explanation]
        **Business**: [High/Medium/Low/None] - [Explanation]
        **Engineering**: [High/Medium/Low/None] - [Explanation]
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: |
        Summarise the reason for the proposal.
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: |
        Explain your proposal in detail and if needed provide options.
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: |
        List out the scope of the work in headline or detailed issue titles.
      value: |
        - Issue
        - Issue
        - Issue
  - type: textarea
    id: questions
    attributes:
      label: Questions
      description: |
        List any questions you have for either the engineering team or managerial team.
      value: |
        - [ENG/MNG] - [Question]
        - [ENG/MNG] - [Question]
        - [ENG/MNG] - [Question]
