name: 📝 Proposal
description: Prepare, track and prioritise proposals for changes to the application.
title: "[Proposal] "
labels: ["📝 planning"]
projects: ["hcsolutions/8"]
body:
  - type: markdown
    attributes:
      value: |
        ## Proposals

        This form provides a tracker issue for a proposal. It is intended to allow work on the proposal to be tracked, and for the proposal to eventually be prioritised/selected.

        The actual _detail_ of the proposal should be captured as a [Discussion](https://github.com/hcsolutions/careportal/discussions/new?category=proposals) with a similar name.
  - type: input
    id: discussion
    attributes:
      label: Discussion
      description: |
        Link to the actual proposal discussion.
      value: "#"
